name: continous deployment

on:
  push:
    brnaches:
      - 'main'

jobs:
  docker-deployment:
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ubuntu
          KEY: ${{ secrets.AWS_HOST_KEY }}
          script: |
            cd entorno-sesion-8
            git pull
            sudo docker compose down
            sudo docker rmi entorno-sesion-8-app
            mvn package -DskipTests
            sudo docker compose up -d